syntax = "proto3";

package session;

option go_package = "session_service/gen";

service SessionService {
  rpc CreateSession (SaveSessionRequest) returns (SaveSessionResponse);
  rpc GetSession (GetSessionRequest) returns (GetSessionResponse);
  rpc DeleteSession (DeleteSessionRequest) returns (DeleteSessionResponse);
}

message SaveSessionRequest {
  int32 userID = 1;
}

message SaveSessionResponse {
  string sessionID = 1;
}

message GetSessionRequest {
  string sessionID = 1;
}

message GetSessionResponse {
  int32 userID = 1;
}

message DeleteSessionRequest {
  string sessionID = 1;
}

message DeleteSessionResponse {
}
